[package]
authors = ["Jacek Całusiński <forger@forger.pl>"]
name = "nanomsg-tokio"
version = "0.1.0"

[dependencies]
chrono = "0.3.0"
colored = "1.4.1"
flexi_logger = "0.5.2"
futures = "0.1.13"
libc = "0.2.21"
log = "0.3.7"
mio = "0.6.6"
nanomsg = "0.6.2"
slog = "2.0.2"
slog-term = "2.0.0-4.0"
tokio-core = "0.1.6"

[dependencies.colored_logger]
optional = false
git = "ssh://git@github.com/FCG-LLC/colored_logger.git"
